global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: 'sergey_salykin'
