version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGODB}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_ db
  ui:
    image: ${USERNAMED}/ui:${VERSION_UI}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAMED}/post:${VERSION_POST}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAMED}/comment:${VERSION_COMMENT}
    networks:
      - back_net
      - front_net
volumes:
  post_db:


networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
  front_net:
    driver: bridge
    ipam:
      driver: default
