kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: yIAOgn5jJltCRiO+jdhbb8f+rPMpMKm9G+oJgHBKVqQ=
      - identity: {}
